stages:
  - build
  - deploy

build:
  stage: build
  image: golang:1.20-alpine
  script:
    - go mod tidy
    - go build -o kirito .
    - docker build -t dika007/kirito:$CI_COMMIT_SHA .
    - docker push dika007/kirito:$CI_COMMIT_SHA

deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - echo "$KUBE_CONFIG" > kubeconfig.yaml
    - kubectl --kubeconfig=kubeconfig.yaml apply -f kubernetes.yml
  only:
    - main
